#!/usr/bin/env python3
"""
plot.py — Read fio sweep results and plot throughput + time-to-read-file vs iodepth.

Reads:   results/sweep-<bs>-<iodepth>.json
Writes:  results/sweep-results.csv
         results/sweep-plot.png          (throughput vs iodepth)
         results/sweep-plot-time.png     (time to read whole file vs iodepth)
"""

# Size of the test file (8 GiB, as generated by gentest).
FILE_SIZE_BYTES = 8 * 1024**3

import glob
import json
import os
import re
import sys

import matplotlib
matplotlib.use("Agg")  # no display needed
import matplotlib.pyplot as plt

RESULTS_DIR = os.environ.get("RESULTS_DIR", "results")

# ---- Collect results --------------------------------------------------------

results = []  # list of (bs, iodepth, bw_kibs, iops, lat_us)

pattern = re.compile(r"sweep-(.+)-(\d+)\.json$")
for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "sweep-*.json"))):
    m = pattern.match(os.path.basename(path))
    if not m:
        continue
    bs = m.group(1)
    iodepth = int(m.group(2))
    with open(path) as f:
        data = json.load(f)
    job = data["jobs"][0]["read"]
    bw_kibs = job["bw"]            # KiB/s
    iops = job["iops"]
    lat_us = job["lat_ns"]["mean"] / 1000  # ns → µs
    results.append((bs, iodepth, bw_kibs, iops, lat_us))

if not results:
    print(f"No sweep-*.json files found in {RESULTS_DIR}/. Run ./sweep.sh first.")
    sys.exit(1)

os.makedirs(RESULTS_DIR, exist_ok=True)

# ---- Write CSV --------------------------------------------------------------

csv_path = os.path.join(RESULTS_DIR, "sweep-results.csv")
with open(csv_path, "w") as f:
    f.write("block_size,iodepth,bw_kibs,bw_mibs,iops,lat_us,time_to_read_s\n")
    for bs, depth, bw, iops, lat in results:
        time_s = FILE_SIZE_BYTES / (bw * 1024)  # bw is KiB/s → bytes/s
        f.write(f"{bs},{depth},{bw},{bw/1024:.1f},{iops:.1f},{lat:.1f},{time_s:.2f}\n")

print(f"Wrote {csv_path} ({len(results)} rows)")

# ---- Plot: throughput vs iodepth, one curve per block size ------------------

# Group by block size.
from collections import defaultdict
by_bs = defaultdict(list)
for bs, depth, bw, iops, lat in results:
    by_bs[bs].append((depth, bw / 1024))  # MiB/s

# Order block sizes small → large.
def bs_key(b):
    units = {"k": 1, "M": 1024, "G": 1024**2}
    num = float(re.match(r"[\d.]+", b).group())
    unit = b[len(re.match(r"[\d.]+", b).group()):]
    return num * units.get(unit[0], 1)

fig, ax = plt.subplots(figsize=(10, 6))
for bs in sorted(by_bs, key=bs_key):
    points = sorted(by_bs[bs])  # by iodepth
    depths = [p[0] for p in points]
    bws = [p[1] for p in points]
    ax.plot(depths, bws, marker="o", label=f"bs={bs}")

ax.set_xlabel("I/O depth (queue parallelism)")
ax.set_ylabel("Throughput (MiB/s)")
ax.set_title("Sequential read throughput: block size × I/O depth")
ax.set_xscale("log", base=2)
ax.set_xticks([1, 4, 8, 16, 32, 64])
ax.set_xticklabels([str(x) for x in [1, 4, 8, 16, 32, 64]])
ax.grid(True, which="both", alpha=0.3)
ax.legend()
fig.tight_layout()
plot_path = os.path.join(RESULTS_DIR, "sweep-plot.png")
fig.savefig(plot_path, dpi=150)
print(f"Wrote {plot_path}")

# ---- Plot: time to read whole file vs iodepth, one curve per block size ------

by_bs_time = defaultdict(list)
for bs, depth, bw, iops, lat in results:
    time_s = FILE_SIZE_BYTES / (bw * 1024)  # bw KiB/s → bytes/s
    by_bs_time[bs].append((depth, time_s))

fig2, ax2 = plt.subplots(figsize=(10, 6))
for bs in sorted(by_bs_time, key=bs_key):
    points = sorted(by_bs_time[bs])  # by iodepth
    depths = [p[0] for p in points]
    times = [p[1] for p in points]
    ax2.plot(depths, times, marker="o", label=f"bs={bs}")

ax2.set_xlabel("I/O depth (queue parallelism)")
ax2.set_ylabel("Time to read 8 GiB file (seconds)")
ax2.set_title("Time to read entire file: block size × I/O depth")
ax2.set_xscale("log", base=2)
ax2.set_xticks([1, 4, 8, 16, 32, 64])
ax2.set_xticklabels([str(x) for x in [1, 4, 8, 16, 32, 64]])
ax2.grid(True, which="both", alpha=0.3)
ax2.legend()
fig2.tight_layout()
time_plot_path = os.path.join(RESULTS_DIR, "sweep-plot-time.png")
fig2.savefig(time_plot_path, dpi=150)
print(f"Wrote {time_plot_path}")
